version: '3'

services:

  bot:
    build:
      context: .
      dockerfile: ./docker/bot/Dockerfile
    container_name: botespontaneidade
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    environment: 
      TZ: "America/Sao_Paulo"
    env_file:
      - config.env      
    restart: unless-stopped
    volumes:
      - ./log:/Log
    depends_on:
      - mysqlsrv  

  mysqlsrv:
    image: mysql:8.0.23
    container_name: botmysqlsrv
    environment: 
      TZ: "America/Sao_Paulo"    
    env_file:
      - config.env    
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql

  botcarga:
    build:
      context: .
      dockerfile: ./docker/carga/Dockerfile
    container_name: botcarga
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    environment: 
      TZ: "America/Sao_Paulo"    
    env_file:
      - config.env      
    restart: unless-stopped
    volumes:
      - ./log:/Log
      - ./Excel:/Excel   
    depends_on:
      - mysqlsrv        

  adminer:
    image: adminer
    container_name: botadminer
    environment: 
      TZ: "America/Sao_Paulo"      
    ports:
      - 8080:8080

  servidorcontagil:
    build:
      context: .
      dockerfile: ./docker/contagil/Dockerfile
    container_name: servidorcontagil
    stdin_open: true # docker run -i
    tty: true        # docker run -t    
    environment: 
      TZ: "America/Sao_Paulo"
    env_file:
      - config.env   
    ports:
      - 1352:1352         
    restart: unless-stopped
    volumes:
      - ./log:/Log
    depends_on:
      - mysqlsrv  

volumes:
  db-data:      
