version: '3'

services:

  botapache:
    build:
        context: .
        dockerfile: ./Dockerfile
    container_name: botapache
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    ports:
        - "8050:80"    
    environment: 
      TZ: "America/Sao_Paulo"
    #env_file:
    #  - config.env      
    restart: "no"
    volumes:
      - ./log:/Log
      - ./public-html/:/usr/local/apache2/htdocs/